# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ARA_Category' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod "CTMediator"
  # Pods for ARA_Category

  target 'ARA_CategoryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ARA_CategoryUITests' do
    # Pods for testing
  end

end
